"""DBMS source content, human-authored. build.py turns it into graph, pool and corpus.

Node:     (id, name, unit, prereqs, [(misconception, belief)], [questions])
Question: (role, level, stem, right, [3 wrong], [misconception index or None per wrong], fact)
role: s standard, d discriminating, c control. `fact` is the corpus sentence the
question cites; build.py checks it survives the provenance check.
"""
TOPIC, TITLE = "dbms", "Database Management Systems"
NODES = [
("relational", "Relational model & keys", "Foundations", [],
 [("keys-unique-only", "believes a primary key only has to be unique, not non-null"),
  ("fk-is-pk", "believes a foreign key must be a primary key of its own table")],
 [("s", 1, "Which attribute set uniquely identifies every row and cannot be NULL?", "Primary key", ["Foreign key", "Any candidate column", "Index column"], [1, None, None],
   "A primary key uniquely identifies each row and can never be NULL."),
  ("s", 2, "A foreign key column in Orders references Customers. Which is true?", "Its values must match an existing Customers key or be NULL", ["It must itself be the primary key of Orders", "It must be unique in Orders", "It must never contain NULL"], [1, 1, None],
   "A foreign key value must match a referenced key or be NULL, and it need not be unique or a primary key."),
  ("s", 2, "Which is a superkey but NOT a candidate key?", "{roll_no, name} when roll_no alone is unique", ["{roll_no}", "Any single column", "The empty set"], [None, None, None],
   "A superkey with a removable attribute is not minimal, so it is not a candidate key."),
  ("s", 3, "R(A,B,C) has candidate keys {A} and {B,C}. How many superkeys contain A?", "4", ["1", "2", "8"], [None, None, None],
   "Every attribute set containing a candidate key is a superkey."),
  ("d", 2, "Can two rows both have primary key value (1, NULL)?", "No: primary key columns cannot be NULL", ["Yes: NULLs are never equal so it is unique", "Yes: uniqueness is all that is required", "Only if the column is indexed"], [0, 0, None],
   "A primary key uniquely identifies each row and can never be NULL."),
  ("c", 2, "Which is a valid primary key value for id INT?", "17", ["NULL", "(NULL, NULL)", "an unset value"], [None, None, None],
   "A primary key uniquely identifies each row and can never be NULL.")]),
("sql", "SQL queries & joins", "Querying", ["relational"],
 [("where-vs-having", "believes WHERE and HAVING are interchangeable"),
  ("null-equals", "believes NULL = NULL evaluates to true")],
 [("s", 1, "Which clause filters rows BEFORE grouping?", "WHERE", ["HAVING", "GROUP BY", "ORDER BY"], [0, None, None],
   "WHERE filters rows before grouping, while HAVING filters groups after aggregation."),
  ("s", 2, "Which query finds departments with more than 5 employees?", "GROUP BY dept HAVING COUNT(*) > 5", ["GROUP BY dept WHERE COUNT(*) > 5", "WHERE COUNT(*) > 5 GROUP BY dept", "ORDER BY COUNT(*) > 5"], [0, 0, None],
   "WHERE filters rows before grouping, while HAVING filters groups after aggregation."),
  ("s", 2, "A LEFT JOIN of A to B returns:", "All rows of A, with NULLs where B has no match", ["Only rows matching in both", "All rows of B", "The cross product"], [None, None, None],
   "A LEFT JOIN keeps every row of the left table and fills NULLs when the right side has no match."),
  ("s", 3, "On 10 rows with 3 NULLs in col, what do COUNT(*) and COUNT(col) return?", "10, 7", ["10, 10", "7, 7", "7, 10"], [1, None, None],
   "COUNT(*) counts rows while COUNT(column) skips NULLs."),
  ("d", 2, "Which returns rows where salary is unknown (NULL)?", "WHERE salary IS NULL", ["WHERE salary = NULL", "WHERE salary == 0", "WHERE NOT salary"], [1, None, None],
   "NULL = NULL evaluates to unknown, so only IS NULL finds NULL values."),
  ("c", 2, "Which returns rows where salary is exactly 5000?", "WHERE salary = 5000", ["WHERE salary IS 5000", "WHERE salary == NULL", "WHERE salary LIKE NULL"], [None, None, None],
   "NULL = NULL evaluates to unknown, so only IS NULL finds NULL values.")]),
("normal", "Normalization", "Design", ["relational"],
 [("more-tables-better", "believes splitting into more tables always improves a design"),
  ("bcnf-3nf-same", "believes 3NF and BCNF are the same thing")],
 [("s", 1, "Which normal form removes partial dependency on part of a composite key?", "2NF", ["1NF", "3NF only", "BCNF only"], [None, None, None],
   "2NF removes partial dependencies of non-key attributes on part of a composite key."),
  ("s", 2, "Deleting one row loses unrelated facts. Which anomaly?", "Deletion anomaly", ["Insertion anomaly", "Update anomaly", "Join anomaly"], [None, None, None],
   "A deletion anomaly means removing one fact also removes another, unrelated fact."),
  ("s", 2, "A relation is in 3NF. Is it always in BCNF?", "No: BCNF is stricter", ["Yes: they are identical", "Yes: 3NF implies BCNF", "Only if it has one key"], [1, 1, None],
   "BCNF is stricter than 3NF: every determinant must be a candidate key."),
  ("s", 3, "R(A,B,C), A->B and B->C, key A. Highest normal form?", "2NF", ["3NF", "BCNF", "1NF only"], [None, None, None],
   "A transitive dependency of a non-key attribute breaks 3NF, leaving the relation in 2NF."),
  ("d", 2, "A design is already in 3NF and every table is split further. Effect on read queries?", "More joins, so reads can get slower", ["Reads always get faster", "Nothing changes", "Joins are no longer needed"], [0, None, None],
   "Extra decomposition beyond need adds joins, so normalization trades write safety against read cost."),
  ("c", 2, "An orders table repeats each customer's address on every row. Splitting customers out:", "Removes redundancy and update anomalies", ["Adds redundancy", "Breaks 1NF", "Removes the need for keys"], [None, None, None],
   "Extra decomposition beyond need adds joins, so normalization trades write safety against read cost.")]),
("index", "Indexing", "Storage", ["relational"],
 [("index-always-faster", "believes adding an index never hurts"),
  ("index-any-column", "believes an index on any column speeds up any query")],
 [("s", 1, "What does an index mainly speed up?", "Lookups by the indexed column", ["Inserts", "Table creation", "Backups"], [0, None, None],
   "An index speeds up lookups on the indexed column but slows inserts and updates."),
  ("s", 2, "What is the cost of adding many indexes?", "Slower writes and more storage", ["Slower reads only", "No cost", "Fewer rows allowed"], [0, None, None],
   "An index speeds up lookups on the indexed column but slows inserts and updates."),
  ("s", 2, "Which index type supports range queries such as BETWEEN?", "B+ tree", ["Hash index", "Bitmap of unique keys", "No index can"], [1, None, None],
   "A B+ tree index supports range queries while a hash index supports only equality."),
  ("s", 3, "Index on (last_name, first_name). Which filter uses it efficiently?", "WHERE last_name = 'Rao'", ["WHERE first_name = 'Asha'", "WHERE first_name LIKE '%a'", "None of them"], [1, None, None],
   "A composite index is used from its leftmost column, so a filter on only the second column cannot use it well."),
  ("d", 2, "A column has two distinct values over a million rows. Does an index help fetch one value?", "Little: it is not selective", ["Yes, always", "Yes, it makes it O(1)", "It shrinks the table"], [1, 0, None],
   "An index helps most when the column is selective, meaning the filter matches few rows."),
  ("c", 2, "A unique id column is looked up one row at a time. An index on it:", "Helps a lot", ["Never helps", "Slows every read", "Is useless for equality"], [None, None, None],
   "An index helps most when the column is selective, meaning the filter matches few rows.")]),
("acid", "Transactions & ACID", "Transactions", ["sql"],
 [("commit-per-statement", "believes each statement inside BEGIN is committed on its own"),
  ("atomic-isolated", "confuses atomicity with isolation")],
 [("s", 1, "Which ACID property means all-or-nothing?", "Atomicity", ["Isolation", "Durability", "Consistency"], [1, None, None],
   "Atomicity means a transaction happens completely or not at all."),
  ("s", 2, "After COMMIT the server crashes and the data survives. Which property?", "Durability", ["Atomicity", "Isolation", "Consistency"], [None, 1, None],
   "Durability means committed changes survive a crash."),
  ("s", 2, "Which property hides one transaction's partial work from another?", "Isolation", ["Atomicity", "Durability", "Consistency"], [1, None, None],
   "Isolation keeps the partial work of one transaction invisible to concurrent transactions."),
  ("s", 3, "A transfer fails after the debit. Recovery must:", "Roll back the debit", ["Keep the debit and retry the credit later", "Delete the account", "Commit the debit"], [None, None, None],
   "If a transaction fails midway, atomicity requires rolling back its partial changes."),
  ("d", 2, "Two statements run inside BEGIN...COMMIT and the second fails. On rollback, the first:", "Is undone too", ["Stays committed", "Is kept as a savepoint", "Is retried"], [0, None, None],
   "Statements inside an explicit transaction commit together, and a rollback undoes them all."),
  ("c", 2, "Autocommit is on and one UPDATE runs outside BEGIN. Is it committed?", "Yes, immediately", ["No, it waits for COMMIT", "Only after a checkpoint", "Only if a second statement runs"], [None, None, None],
   "Statements inside an explicit transaction commit together, and a rollback undoes them all.")]),
("concurrency", "Concurrency & deadlocks", "Transactions", ["acid"],
 [("cycle-deadlock", "believes any cycle in any graph means deadlock"),
  ("serial-only", "believes only serial execution is correct")],
 [("s", 1, "A deadlock shows as a cycle in which graph?", "Wait-for graph", ["ER diagram", "B+ tree", "Call graph"], [0, None, None],
   "A deadlock appears as a cycle in the wait-for graph of transactions."),
  ("s", 2, "Two transactions each hold a lock the other needs. This is:", "A deadlock", ["A dirty read", "A checkpoint", "A phantom"], [None, None, None],
   "A deadlock appears as a cycle in the wait-for graph of transactions."),
  ("s", 2, "Which schedule is correct even though it is not serial?", "A conflict-serializable schedule", ["Any interleaved schedule", "Only a serial schedule", "A schedule with a cycle"], [None, 1, None],
   "A conflict-serializable schedule is equivalent to some serial schedule, so it is correct."),
  ("s", 3, "Strict two-phase locking guarantees:", "Serializability and no cascading aborts", ["Deadlock freedom", "No waiting", "Only durability"], [0, None, None],
   "Strict two-phase locking gives serializable schedules without cascading aborts but does not prevent deadlock."),
  ("d", 2, "A resource-allocation graph has a cycle and each resource has several instances. Necessarily deadlock?", "No: a cycle is necessary, not sufficient", ["Yes: a cycle always means deadlock", "Yes, if any transaction waits", "No cycle can occur"], [0, 0, None],
   "With several instances per resource, a cycle in the graph is necessary for deadlock but not sufficient."),
  ("c", 2, "A wait-for graph of single-instance locks has a cycle. Deadlock?", "Yes", ["No", "Only after a timeout", "Only for read locks"], [None, None, None],
   "With several instances per resource, a cycle in the graph is necessary for deadlock but not sufficient.")]),
("optimizer", "Query optimization", "Storage", ["index", "sql"],
 [("optimizer-follows-writing", "believes the database runs a query exactly as written"),
  ("select-star-free", "believes SELECT * costs the same as selecting needed columns")],
 [("s", 1, "What does EXPLAIN show?", "The chosen query plan", ["The table data", "The index size only", "The lock table"], [None, None, None],
   "EXPLAIN shows the query plan the optimizer chose."),
  ("s", 2, "Does the table order in a JOIN clause fix the order tables are read?", "No: the optimizer may reorder joins", ["Yes: always as written", "Yes for INNER JOIN", "Only with an index"], [0, 0, None],
   "The optimizer may reorder joins and pick access paths regardless of how the query was written."),
  ("s", 2, "What most often stops a filter on col from using its index?", "Wrapping col in a function such as UPPER(col)", ["Using an integer", "Adding ORDER BY", "Using AND"], [None, None, None],
   "Applying a function to an indexed column in the filter usually prevents the index from being used."),
  ("s", 3, "A cost-based optimizer chooses:", "The plan with the lowest estimated cost", ["The first plan found", "The plan the user wrote", "The plan using most indexes"], [0, 0, None],
   "A cost-based optimizer picks the plan with the lowest estimated cost from statistics."),
  ("d", 2, "Selecting all columns when two are needed, on a wide table, can:", "Prevent an index-only scan and read more data", ["Cost nothing extra", "Always use the index", "Skip the disk"], [1, None, None],
   "Selecting unneeded columns can prevent index-only scans and forces more data to be read."),
  ("c", 2, "A query needs every column of every row. SELECT * versus listing all columns:", "Same work", ["Listing is much faster", "SELECT * fails", "SELECT * skips rows"], [None, None, None],
   "Selecting unneeded columns can prevent index-only scans and forces more data to be read.")]),
]

# Extra standard questions, so a drilldown does not run dry. `fact` is an index into
# the node's distinct facts (in order of first appearance).
EXTRA = {
"relational": [("s", 1, "A candidate key is:", "A minimal set of attributes that uniquely identifies rows", ["Any column with an index", "A column that may repeat", "A foreign key"], [None, None, None], 0),
               ("s", 2, "Which value can a foreign key column hold?", "A matching key value or NULL", ["Any integer", "Only a primary key of its own table", "Only unique values"], [None, 1, None], 1)],
"sql": [("s", 1, "Which join returns only rows that match in both tables?", "INNER JOIN", ["LEFT JOIN", "CROSS JOIN", "FULL JOIN without ON"], [None, None, None], 2),
        ("s", 2, "To keep only groups whose SUM(sales) exceeds 1000 you use:", "HAVING SUM(sales) > 1000", ["WHERE SUM(sales) > 1000", "GROUP BY SUM(sales)", "ORDER BY 1000"], [0, None, None], 0)],
"normal": [("s", 1, "First normal form requires:", "Atomic values in every column", ["No foreign keys", "Only one table", "Sorted rows"], [None, None, None], 0),
           ("s", 2, "Which dependency does 3NF remove?", "Transitive dependency of a non-key attribute", ["Any functional dependency", "All keys", "Multi-valued columns only"], [None, None, None], 3)],
"index": [("s", 1, "Where is a B+ tree index most useful?", "Range and equality lookups", ["Storing backups", "Compressing text", "Deleting tables"], [None, None, None], 2),
          ("s", 2, "Why can an index slow an UPDATE?", "The index entries must be updated too", ["Indexes lock the whole disk", "UPDATE ignores indexes", "Indexes are read-only"], [0, None, None], 0)],
"acid": [("s", 1, "Which property keeps the database valid according to its rules?", "Consistency", ["Durability", "Isolation", "Atomicity"], [None, None, 1], 0),
         ("s", 2, "COMMIT makes changes:", "Permanent and visible to others", ["Temporary until logout", "Invisible forever", "Undoable by ROLLBACK later"], [None, None, None], 1)],
"concurrency": [("s", 1, "Which technique prevents conflicting concurrent access using locks?", "Two-phase locking", ["Normalization", "Hashing", "Indexing"], [None, None, None], 3),
                ("s", 2, "Deadlock is usually resolved by:", "Aborting one transaction as a victim", ["Waiting forever", "Committing both", "Dropping the table"], [None, None, None], 0)],
"optimizer": [("s", 1, "Which statistic most helps a cost-based optimizer?", "Row counts and value distributions", ["Table colour", "Column order in SELECT", "Username"], [None, None, None], 3),
              ("s", 2, "A full table scan is chosen over an index when:", "The filter matches a large fraction of rows", ["The table has an index", "The query has ORDER BY", "Statistics are fresh"], [None, None, None], 1)],
}
