"""DSA source content. Same format as dbms.py."""
TOPIC, TITLE = "dsa", "Data Structures & Algorithms"
NODES = [
("complexity", "Complexity analysis", "Foundations", [],
 [("bigo-is-time", "believes Big-O gives the exact running time"),
  ("worst-only", "believes average and worst case are always the same")],
 [("s", 1, "What does O(n) describe?", "Growth of cost with input size, up to a constant", ["The exact running time in seconds", "The memory address used", "The number of lines of code"], [0, None, None],
   "Big-O describes how cost grows with input size and ignores constant factors."),
  ("s", 2, "Which is asymptotically faster for large n?", "O(n log n)", ["O(n^2)", "O(2^n)", "O(n!)"], [None, None, None],
   "Growth order is n log n below n squared below 2 to the n."),
  ("s", 3, "Loop i from 1 to n, doubling i each time. How many iterations?", "About log2 n", ["n", "n/2", "sqrt n"], [None, None, None],
   "A loop that doubles its counter runs about log base two of n times."),
  ("d", 2, "Algorithm A is O(n) and B is O(n^2). For n = 5, can B be faster in practice?", "Yes: constants can dominate for small n", ["No: O(n) always wins", "No: Big-O is exact time", "Only if n is negative"], [0, None, None],
   "Big-O describes how cost grows with input size and ignores constant factors."),
  ("c", 2, "Doubling n for an O(n^2) algorithm multiplies the work by about:", "4", ["2", "8", "1"], [None, None, None],
   "Big-O describes how cost grows with input size and ignores constant factors.")]),
("linear", "Arrays, stacks & queues", "Structures", ["complexity"],
 [("stack-fifo", "believes a stack removes the oldest element first"),
  ("array-insert-o1", "believes inserting in the middle of an array is O(1)")],
 [("s", 1, "Which structure is last-in first-out?", "Stack", ["Queue", "Array only", "Heap"], [0, None, None],
   "A stack is last-in first-out while a queue is first-in first-out."),
  ("s", 2, "Cost of inserting at the front of an array of n items?", "O(n)", ["O(1)", "O(log n)", "O(n log n)"], [1, None, None],
   "Inserting in the middle of an array shifts elements, so it costs O(n)."),
  ("s", 3, "Push 1,2,3 then pop, pop onto a stack. What is on top?", "1", ["2", "3", "empty"], [0, None, None],
   "A stack is last-in first-out while a queue is first-in first-out."),
  ("d", 2, "Push A, B, C onto a stack, then pop once. Which is removed?", "C", ["A", "B", "Any of them"], [0, None, None],
   "A stack is last-in first-out while a queue is first-in first-out."),
  ("c", 2, "Enqueue A, B, C into a queue, then dequeue once. Which is removed?", "A", ["C", "B", "Any of them"], [None, None, None],
   "A stack is last-in first-out while a queue is first-in first-out.")]),
("sorting", "Sorting algorithms", "Algorithms", ["complexity", "linear"],
 [("quick-always-fast", "believes quicksort is always O(n log n)"),
  ("stable-means-fast", "confuses a stable sort with a fast sort")],
 [("s", 1, "Worst-case time of merge sort?", "O(n log n)", ["O(n)", "O(n^2)", "O(log n)"], [None, None, None],
   "Merge sort takes O(n log n) in every case."),
  ("s", 2, "Which sort is stable?", "Merge sort", ["Heap sort", "Standard quicksort", "Selection sort"], [None, None, None],
   "A stable sort keeps equal keys in their original order, and merge sort is stable."),
  ("s", 3, "Quicksort with the first element as pivot on an already sorted array runs in:", "O(n^2)", ["O(n log n)", "O(n)", "O(log n)"], [0, None, None],
   "Quicksort degrades to O(n squared) when pivots split the input badly, for example a sorted array with a first-element pivot."),
  ("d", 2, "Is quicksort always O(n log n)?", "No: bad pivots give O(n^2)", ["Yes, always", "Yes, on average and worst case", "Yes if n is small"], [0, 0, None],
   "Quicksort degrades to O(n squared) when pivots split the input badly, for example a sorted array with a first-element pivot."),
  ("c", 2, "Average-case time of quicksort with random pivots?", "O(n log n)", ["O(n^2)", "O(n)", "O(log n)"], [None, None, None],
   "Quicksort degrades to O(n squared) when pivots split the input badly, for example a sorted array with a first-element pivot.")]),
("hashing", "Hash tables", "Structures", ["complexity", "linear"],
 [("hash-always-o1", "believes hash lookup is always O(1)"),
  ("hash-ordered", "believes a hash table keeps keys in sorted order")],
 [("s", 1, "Average cost of a hash table lookup?", "O(1)", ["O(n)", "O(log n)", "O(n log n)"], [None, None, None],
   "A hash table lookup is O(1) on average and O(n) when all keys collide."),
  ("s", 2, "What is a collision?", "Two keys hashing to the same slot", ["A full table", "A deleted key", "A sorted bucket"], [None, None, None],
   "A collision is two different keys mapping to the same slot."),
  ("s", 3, "All keys collide into one bucket kept as a list. Lookup cost?", "O(n)", ["O(1)", "O(log n)", "O(n^2)"], [0, None, None],
   "A hash table lookup is O(1) on average and O(n) when all keys collide."),
  ("d", 2, "Does iterating a hash table give keys in sorted order?", "No: order is not sorted", ["Yes, always", "Yes for integer keys only", "Yes if it is resized"], [1, 1, None],
   "A hash table does not keep keys in sorted order."),
  ("c", 2, "You need a fast lookup by key and do not care about order. A hash table:", "Fits well", ["Cannot do lookups", "Requires sorted input", "Is slower than a linear scan"], [None, None, None],
   "A hash table does not keep keys in sorted order.")]),
("trees", "Trees & BSTs", "Structures", ["linear"],
 [("bst-balanced", "believes every BST has height log n"),
  ("inorder-any", "believes inorder traversal of any binary tree is sorted")],
 [("s", 1, "Inorder traversal of a BST visits keys in what order?", "Sorted ascending", ["Insertion order", "Level order", "Random order"], [None, None, None],
   "Inorder traversal of a binary search tree visits keys in ascending order."),
  ("s", 2, "Search cost in a balanced BST of n nodes?", "O(log n)", ["O(1)", "O(n)", "O(n log n)"], [None, None, None],
   "A balanced binary search tree has height about log n, so search is O(log n)."),
  ("s", 3, "Insert keys 1,2,3,4,5 in order into an unbalanced BST. Search for 5 costs:", "O(n)", ["O(log n)", "O(1)", "O(n log n)"], [0, None, None],
   "An unbalanced BST built from sorted input degenerates into a list, so search is O(n)."),
  ("d", 2, "A BST is built by inserting sorted keys. Its height is about:", "n", ["log n", "1", "sqrt n"], [0, None, None],
   "An unbalanced BST built from sorted input degenerates into a list, so search is O(n)."),
  ("c", 2, "A perfectly balanced BST has 15 nodes. Its height (levels) is:", "4", ["15", "8", "2"], [None, None, None],
   "A balanced binary search tree has height about log n, so search is O(log n).")]),
("graphs", "Graph traversal", "Algorithms", ["linear", "trees"],
 [("bfs-dfs-same", "believes BFS and DFS visit nodes in the same order"),
  ("dfs-shortest", "believes DFS finds shortest paths in unweighted graphs")],
 [("s", 1, "Which structure does BFS use?", "Queue", ["Stack", "Heap", "Hash set only"], [1, None, None],
   "Breadth-first search uses a queue and depth-first search uses a stack."),
  ("s", 2, "Which finds shortest paths by edge count in an unweighted graph?", "BFS", ["DFS", "Inorder traversal", "Either, always"], [1, None, 1],
   "Breadth-first search finds shortest paths by edge count in an unweighted graph, and depth-first search does not."),
  ("s", 3, "Time to run BFS on a graph with V vertices and E edges (adjacency list)?", "O(V + E)", ["O(V)", "O(E^2)", "O(V * E)"], [None, None, None],
   "Breadth-first search on an adjacency list takes O(V plus E) time."),
  ("d", 2, "Does DFS from A always reach a node by the fewest edges?", "No: it may take a longer path", ["Yes, always", "Yes in any graph", "Yes if it uses recursion"], [1, 1, None],
   "Breadth-first search finds shortest paths by edge count in an unweighted graph, and depth-first search does not."),
  ("c", 2, "You need the fewest hops between two nodes of an unweighted graph. Use:", "BFS", ["Sorting", "Hashing", "Inorder traversal"], [None, None, None],
   "Breadth-first search finds shortest paths by edge count in an unweighted graph, and depth-first search does not.")]),
]

EXTRA = {
"complexity": [("s", 1, "Which is the fastest growing?", "O(2^n)", ["O(n)", "O(log n)", "O(n log n)"], [None, None, None], 0),
               ("s", 2, "Binary search on n sorted items takes:", "O(log n)", ["O(n)", "O(1)", "O(n^2)"], [None, None, None], 2)],
"linear": [("s", 1, "Which structure is first-in first-out?", "Queue", ["Stack", "Binary tree", "Hash table"], [0, None, None], 0),
           ("s", 2, "Random access by index in an array costs:", "O(1)", ["O(n)", "O(log n)", "O(n^2)"], [1, None, None], 1)],
"sorting": [("s", 1, "Which sort repeatedly picks the minimum of the remaining items?", "Selection sort", ["Merge sort", "Quicksort", "Counting sort"], [None, None, None], 0),
            ("s", 2, "Which property keeps equal keys in original order?", "Stability", ["Speed", "In-place", "Recursion"], [1, None, None], 1)],
"hashing": [("s", 1, "A good hash function should:", "Spread keys evenly across slots", ["Sort the keys", "Map all keys to one slot", "Be slow"], [1, None, None], 1),
            ("s", 2, "Chaining resolves collisions by:", "Keeping a list of entries per slot", ["Deleting old keys", "Sorting the table", "Doubling every key"], [None, None, None], 1)],
"trees": [("s", 1, "In a BST the left child key is:", "Smaller than the parent", ["Larger than the parent", "Equal to the parent", "Random"], [None, None, None], 0),
          ("s", 2, "Worst-case search in an unbalanced BST of n nodes?", "O(n)", ["O(1)", "O(log n)", "O(n log n)"], [0, None, None], 2)],
"graphs": [("s", 1, "Which structure does DFS use?", "Stack (or recursion)", ["Queue", "Heap", "Sorted array"], [0, None, None], 0),
           ("s", 2, "BFS visits nodes in order of:", "Distance from the start (edge count)", ["Depth first", "Alphabet", "Random order"], [0, None, None], 1)],
}
